#!/usr/bin/perl
use 5.010;
sub greet {
	state $last;
	$name = @_[0];
	if (!$last) {
		print "Hi $name! You are the first one here!\n";
		$last = $name;
	} else {
		print "Hi $name! $last is also here!\n";
		$last = $name;
	}
}

greet( "Fred" );
greet( "Barney" );
